version: '3.6'
services:
  connect_api:
    build: .
    command: yarn dev
    volumes:
        - .:/usr/app/
        - /usr/app/node_modules
    environment:
        NODE_ENV: "development"
        # DB_MONGODB_NAME_TEST: "currency_api_test"
        MYSQL_ROOT_PASSWORD: "admin"
        MYSQL_USER: "test"
        MYSQL_HOST: "mysql"
        MYSQL_PASSWORD: "test123@"
        MYSQL_DATABASE: "connect_db"
        PORT: 8888
        LOGGER_LEVEL: debug
    ports:
        - "8888:8888"
    depends_on:
        - mysql
  mysql:
    image: "mysql:5.7.37"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "test123@"
      MYSQL_DATABASE: "connect_db"
