version: '3.6'
services:
  connect_api:
    container_name: connect_api
    build: .
    command: yarn dev
    volumes:
        - .:/usr/app/
        - /usr/app/node_modules
    environment:
        NODE_ENV: "development"
        CLEARDB_DATABASE_URL: mysql://root:admin@mysql/connect_db
        PORT: 8888
        LOGGER_LEVEL: debug
    ports:
        - "8888:8888"
    depends_on:
        - mysql
  mysql:
    platform: linux/x86_64 # just mac m1
    image: "mysql:5.7.37"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "connect_db"
